# Generated by Django 5.1.2 on 2024-11-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attempt",
            options={
                "ordering": ["status", "newsletter", "date_of_attempt"],
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "ordering": ["status", "message"],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "ordering": ["name"],
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
        migrations.AlterField(
            model_name="attempt",
            name="status",
            field=models.CharField(
                choices=[("Успешно", "Успешно"), ("Не успешно", "Не успешно")],
                default="Успешно",
                verbose_name="Статус попытки рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="date_of_end_shipment",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата и время окончания рассылки"),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="status",
            field=models.CharField(
                choices=[
                    ("Завершена", "Завершена"),
                    ("Создана", "Создана"),
                    ("Запущена", "Запущена"),
                ],
                default="Создана",
                verbose_name="Статус рассылки",
            ),
        ),
    ]
