# Generated by Django 5.1.2 on 2024-11-24 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0003_attempt_owner_message_owner_newsletter_owner_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "ordering": ["status", "message"],
                "permissions": [("can_stop_newsletter", "can stop newsletter")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
