# Generated by Django 5.1.2 on 2024-11-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0004_alter_newsletter_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="date_of_first_shipment",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата и время начала рассылки"
            ),
        ),
    ]
